#!/bin/bash
# Skip generation when running SwiftUI previews
if [ "$ENABLE_PREVIEWS" = "YES" ]; then
    echo "⚠️ Skipping Firebase constants generation for SwiftUI previews."
    exit 0
fi
set -e

echo "🚧 Generating Image Constants..."

ROOT_DIR="${SRCROOT}/RickAndMorty"
ASSETS_PATH="${ROOT_DIR}/Resources/Images.xcassets"
OUTPUT_PATH="${ROOT_DIR}/Utils/Constants/ImageConstants.swift"

# Header for the Swift file
HEADER="// Auto-generated file. Do not edit manually.
// Generated by update_image_constants.sh
// Date: $(date)

import SwiftUI

extension Image {
"

# Find all image sets (excluding AppIcon) and sort them alphabetically
IMAGE_NAMES=$(find "$ASSETS_PATH" -type d -name "*.imageset" -exec basename {} .imageset \; | grep -v "^AppIcon$" | sort)

# Start writing the file
echo "$HEADER" > "$OUTPUT_PATH"

# Add each image constant
for IMAGE in $IMAGE_NAMES; do
    SAFE_NAME=$(echo "$IMAGE" | sed 's/[^a-zA-Z0-9_]/_/g') # Make safe Swift identifier
    echo "    //$SAFE_NAME" >> "$OUTPUT_PATH"
    echo "    static let $SAFE_NAME = Image(\"$IMAGE\")" >> "$OUTPUT_PATH"
done

# Close extension
echo "}" >> "$OUTPUT_PATH"

echo "✅ ImageConstants.swift updated with $(echo "$IMAGE_NAMES" | wc -l) images."
